### PR TITLE
MDE/feature/Menu

### PR DESCRIPTION
**Pull request by mantvydasdeltuva**
# Initial (2024-12-24)
- [MDE/feature/Menu Imported new icons and dimensions](https://github.com/mantvydasdeltuva/guidal/commit/9746429b20ef59c1e13063e7dfecc63a3e08d228)
- [MDE/feature/Menu Implemented menu button composable](https://github.com/mantvydasdeltuva/guidal/commit/6e1b3e0150bc4b5ed98e8c2edd4b084dd4fd34a5)
- [MDE/feature/Menu Implemented menu main screen](https://github.com/mantvydasdeltuva/guidal/commit/29b58e923f25417535adbcd9d269c209fdc51545)
- [MDE/feature/Menu Adjusted top app bar default height](https://github.com/mantvydasdeltuva/guidal/commit/eaa786159b02626c089196bb2fad7dc238a98096)
- [MDE/feature/Menu Extracted most string resources from MainScreen.kt](https://github.com/mantvydasdeltuva/guidal/commit/de3f494a35f8501dccc6a636beee32fa2a3c43e7)

### CODE REVIEW

**Review by justinnas — CHANGES_REQUESTED** [review]
Most things look great, but I found a bug. If you click "Profile" and go back and click "Profile" again, it works fine. But, if you click "Profile", then go back and click, for example, "About" and then try clicking on "Profile" again, it no longer does anything.

**Comment by mantvydasdeltuva** [comment]
@justinnas currently it's intended behaviour because clicking on other navigation options would block any attempts to go to other or same (spam click) navigation. As of right now, other navigations are not present thus, blocks without navigating. Wouldn't be a problem after the navigation is sorted out

**Comment by justinnas** [comment]
Makes sense, works as intended then!

**Review by justinnas — APPROVED** [review]
Great job!

**Pull request merged**
